trigger: none

variables:
  front_end_cache: '$(Build.SourcesDirectory)'

pool: 'self-hosted-agent-win'

# stages:
#   - stage: Build
#     pool: 'self-hosted-machine'
#     jobs:
#       - job: Build
#         displayName: "Angular App Build"
#         workspace:
#           clean: all

steps:  
  - task: Cache@2
    displayName: 'cache for frontend'
    inputs:
      key: $(Build.SourcesDirectory)/package-lock.json
      path: '$(front_end_cache)'
      cacheHitVar: 'CACHE_RESTORED'
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        node -v
        npm -v 
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js"       
  - task: Npm@1
    inputs:
      command: "install"
      workingDir: '$(front_end_cache)'
    displayName: "Npm Install"
  - task: Npm@1
    inputs:
      command: custom
      customCommand: "run build"
      workingDir: '$(front_end_cache)'
    displayName: "Build Angular app"
  # - task: Npm@1
  #   inputs:
  #     command: custom
  #     customCommand: "run test"
  #   displayName: "Test Angular app"
  - task: Npm@1
    inputs:
      command: custom
      customCommand: "run lint"
      workingDir: '$(front_end_cache)'
    displayName: "Lint Angular app"
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory/dist'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      CleanTargetFolder: true
      flattenFolders: true
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: DemoApplication
      publishLocation: Container
  # - script: |
  #     mkdir $(Build.ArtifactStagingDirectory)\\dist
  #     xcopy "dist\\sample-app" $(Build.ArtifactStagingDirectory)\\dist /E/H/C
  #   displayName: Copy dist contents
  # - task: PublishBuildArtifacts@1
  #   displayName: "Publish Artifact"
  - task: CmdLine@2
    inputs:
      script: |
        node -v
        npm -v

  # - stage: Deploy
  #   dependsOn: Build
  #   condition: succeeded('Build')
  #   variables:
  #     - group: SECRET-DEV
  #     - group: VGRP-DEV
  #   pool:
  #     vmImage: 'windows-latest'
  #   jobs:
  #     - deployment: Deploy
  #       displayName: Deploy to Azure
  #       environment: DEV
  #       strategy:
  #         runOnce:
  #           deploy:
  #             steps:
  #               - task: AzureCLI@2
  #                 displayName: "Deploy Angular app"
  #                 inputs:
  #                   azureSubscription: $(azureSubscription)
  #                   scriptType: batch
  #                   scriptLocation: inlineScript
  #                   inlineScript: |
  #                     az storage blob upload-batch --overwrite -d $web --account-name $(storageAccount) --account-key $(accountkey) -s "$(Agent.BuildDirectory)\\drop\\dist"
